---
title: "engression_worksheet"
author: "Philip Boustani"
date: "2024-03-24"
output: html_document
---

# Setup Rmarkdown

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# install packages

```{r}
# List of required packages
packages <- c(
  "engression",
  "sn" # for simulating skewed normals
)

# First, installing packages which are not yet installed and then loading all of them
for (pkg in packages) {
  if(!require(pkg, character.only = TRUE)){
    install.packages(pkg, character.only = TRUE);
    library(pkg, character.only = TRUE)
  }
}
```

# simulate data

```{r}
######
n = 1000; p=1 ## n samples and p dimensional covariate 
beta = 4+rnorm(p) ## random regression coefficients 
X = matrix(rnorm(n*p), ncol=p) ## design matrix 
Y = X %*% beta + rnorm(n) ## linear model
plot(X[,1],Y)
```

```{r}
# test data are slightly shifted
Xtest = matrix(1 + rnorm(n*p), ncol=p)
Ytest = Xtest %*% beta + rnorm(n)
plot(Xtest[,1], Ytest)
```

# run engression

```{r}
# fit an engression model for Y~X
engression_YX = engression(X, Y) 

# predict on training data 
yhat = predict(engression_YX, Xtest)


plot(Xtest, Ytest, col = rgb(0, 0, 0, alpha = 0.4), pch = 16)

points(Xtest, yhat, col = rgb(1, 0, 0, alpha = 0.9), pch = 16)

```


```{r}
# predict on test data 
yhatEngression = predict(engression_YX, Xtest) 

# evaluate conditional mean prediction on test data
mean((yhatEngression - Ytest)^2) 

# quantile prediction with the same engression object 
# quantile_pred <- predict(engressionFit, Xtest, type="quantile", 
#        quantiles=c(0.1, 0.5, 0.9))
```

```{r}
# Plot the original data points
plot(Xtest[,1], Ytest)

# Add the points of yhatRegression to the plot in red
points(Xtest[,1], yhatEngression, col = "red")
```

```{r}
res_YX <- yhatEngression - Ytest
cor(Xtest, res_YX)
```

```{r}
engression_XY = engression(Y,X)
```

```{r}
# predict on test data 
Ytest_range <- seq(min(Ytest),max(Ytest),length.out=200)
xhatEngression = predict(engression_XY, Ytest_range)
xhat_quantile <- predict(engression_XY, Ytest_range, type="quantile", 
  quantiles=c(0.05, 0.95))
```

```{r}
# create Plot 
plot(Ytest, Xtest[,1], type = 'n')


# plot the confidence interval 
polygon(c(rev(Ytest_range), Ytest_range), 
        c(rev(xhat_quantile[,2]), xhat_quantile[,1]), 
        col = rgb(1, 0, 0, alpha = 0.4), 
        border = NA
      )


# Plot the original data points
points(Ytest, Xtest[,1], col = rgb(0, 0, 0, alpha = 0.4), pch = 16)


# add mean preditcion
lines(Ytest_range, xhatEngression, col = rgb(1, 0, 0, alpha = 0.7), lwd=3)

```

```{r}
# test for independence of residuals and regressors
res_XY <- xhatEngression - Xtest
cor(Ytest, res_XY)
```



# Simulate heteroscedastic data

```{r}
# for skewed normals
library(sn)
```


```{r}
n <- 10^4
m <- 4 # for the max value of X 
X <- runif(n, 0,m)

# Y <- rnorm(n,mean=3*X,sd=(X-0.5*m)^2)
Y <- rsn(n=n, xi=3*X, omega=-(X-0.5*m)^2+4, alpha=100, tau=0, dp=NULL)
Y <- as.vector(Y)

hs_eng = engression(X,Y)
```


```{r}
# predict mean and quantiles 
X_range <- seq(min(X),max(X),length.out=200)
Yhat_eng = predict(hs_eng, X_range)
Yhat_quantile <- predict(hs_eng, X_range, type="quantile", 
                         quantiles=c(0.05,0.2,0.5,0.8, 0.95)
                         )
# Yhat_median <- predict(hs_eng, X_range, type="quantile", 
#   quantiles=c(0.5))
```


```{r}
# create Plot 
plot(X, Y, type = 'n')

# Plot the original data points
plot_sample <- rbinom(n,1,0.2)
points(X[plot_sample==1], Y[plot_sample==1], col = rgb(0, 0, 0, alpha = 0.4), pch = 16)


# plot the confidence interval 
polygon(c(rev(X_range), X_range), 
        c(rev(Yhat_quantile[,5]), Yhat_quantile[,1]), 
        col = rgb(1, 0, 0, alpha = 0.4), 
        border = NA
      )

polygon(c(rev(X_range), X_range), 
        c(rev(Yhat_quantile[,4]), Yhat_quantile[,2]), 
        col = rgb(1, 0, 0, alpha = 0.6), 
        border = NA
      )

# add mean prediction
lines(X_range, Yhat_eng, col = rgb(0, 0, 1, alpha = 0.7), lwd=3)

# add median prediction
lines(X_range, Yhat_quantile[,3], col = rgb(0, 1, 0, alpha = 0.7), lwd=3)
```











