---
title: "PrePostANMexampleplots"
author: "Philip Boustani"
date: "2024-08-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
g <- function(x) x^3/10
X <- seq(-10, 10, length.out=10^4)
Y <- g(X)
```


```{r}
Xeval <- seq(-2.5, 2.5, length.out=10^3)
Yeval <- g(Xeval)

m <- 20
Xrand <- c(-2.5, runif(m,-2.4,2.4),2.5)
Ytrue <- g(Xrand)
Yrand <- g(Xrand) + runif(m+2,-2,2)
```


```{r}
# specify export file name
fig_name <- "PertubationPlot_postANM"

# Specify export folder
project_folder <- "D:/PAB/Nextcloud/PA/06_UNIGE/master_thesis/icp-engression/"
figure_folder <- "writing/figures/"
figure_dir <- paste(project_folder,figure_folder, sep = "" )

# Open EPS device
postscript(paste(figure_dir, fig_name, ".eps", sep = ""),
           width = 5, height = 4, horizontal = FALSE)

par(mar = c(3, 3, 0.1, 0.1)) # default: par(mar = c(5.1, 4.1, 4.1, 2.1))   

plot(X, Y, 
     xlim=c(-4,4), ylim=c(-4,4), 
     type = "l", col = "seashell4", lty = 2, lwd = 2, 
     xlab = "", ylab = "", xaxt = "n", yaxt = "n", bty = "n", ann = FALSE)

lines(Xeval, Yeval, col = "violetred3", lwd = 3)

segments(x0 = Xrand, y0 = Ytrue, x1 = Xrand, y1 = Yrand, 
         col = "violetred1", lwd = 1, lty = 3)
  
points(Xrand,Ytrue, col = "pink", cex = 1.2, pch = 19)
points(Xrand,Yrand, col = "pink4", cex = 1.2, pch = 19)

axis(1, at=-4:4)
axis(2, at=-4:4)
mtext("X", side = 1, line = 2)
mtext("Y", side = 2, line = 2)

legend("topleft", 
       legend = c("true f", "evaluated f", "residuals", "true Y", "distorted Y"), 
       col = c("seashell4", "violetred3", "violetred1", "pink", "pink4"), 
       lty = c(2, 1, 3, NA, NA), lwd = c(2, 3, 1, NA, NA), 
       pch = c(NA, NA, NA, 19, 19), 
       pt.cex = c(NA, NA, NA, 1.5, 1.5), 
       bty = "n")

dev.off()
```


```{r}
m <- 20
Yrand <- rnorm(m,0,1.5)
indices <- lapply(Yrand, function(y) which(round(Y,2)== round(y,2)))
result <- unlist(lapply(indices, function(x) x[1]))
Xtrue <- X[result]
Xrand <- Xtrue + runif(m,-2,2)

Xeval <- seq(min(Xtrue), max(Xtrue), length.out=10^3)
Yeval <- g(Xeval)
```


```{r}
# specify export file name
fig_name <- "PertubationPlot_preANM"

# Specify export folder
project_folder <- "D:/PAB/Nextcloud/PA/06_UNIGE/master_thesis/icp-engression/"
figure_folder <- "writing/figures/"
figure_dir <- paste(project_folder,figure_folder, sep = "" )

# Open EPS device
postscript(paste(figure_dir, fig_name, ".eps", sep = ""),
           width = 5, height = 4, horizontal = FALSE)

par(mar = c(3, 3, 0.1, 0.1)) # default: par(mar = c(5.1, 4.1, 4.1, 2.1))   

plot(X, Y, 
     xlim=c(-4,4), ylim=c(-4,4), 
     type = "l", col = "seashell3", lty = 2, lwd = 2, 
     xlab = "", ylab = "", xaxt = "n", yaxt = "n", bty = "n", ann = FALSE)

lines(Xeval, Yeval, col = "violetred3", lwd = 3)

segments(x0 = Xtrue, y0 = Yrand, x1 = Xrand, y1 = Yrand,
         col = "violetred1", lwd = 1, lty = 3)

points(Xtrue,Yrand, col = "pink2", cex = 1.2, pch = 19)
points(Xrand,Yrand, col = "pink4", cex = 1.2, pch = 19)

axis(1, at=-4:4)
axis(2, at=-4:4)
mtext("X", side = 1, line = 2)
mtext("Y", side = 2, line = 2)

legend("topleft", 
       legend = c("true f", "evaluated f", "residuals", "true Y", "distorted Y"), 
       col = c("seashell4", "violetred3", "violetred1", "pink", "pink4"), 
       lty = c(2, 1, 3, NA, NA), lwd = c(2, 3, 1, NA, NA), 
       pch = c(NA, NA, NA, 19, 19), 
       pt.cex = c(NA, NA, NA, 1.5, 1.5), 
       bty = "n")

dev.off()
```







```{r}
m <- 15
Xtrue <- seq(-2.8, 2.8, length.out = m+2)
noise <-c(0,runif(m,-0.2,0.2), 0)
Xtrue <- Xtrue + noise
Ytrue <- g(Xtrue)
Xrand <- Xtrue + runif(m+2,-1.5,1.5)

Xeval <- seq(min(Xtrue), max(Xtrue), length.out=10^3)
Yeval <- g(Xeval)

par(mar = c(3, 3, 0.1, 0.1)) # default: par(mar = c(5.1, 4.1, 4.1, 2.1))   

plot(X, Y, 
     xlim=c(-4,4), ylim=c(-4,4), 
     type = "l", col = "seashell3", lty = 2, lwd = 2, 
     xlab = "", ylab = "", xaxt = "n", yaxt = "n", bty = "n", ann = FALSE)

lines(Xeval, Yeval, col = "violetred3", lwd = 3)

segments(x0 = Xtrue, y0 = Ytrue, x1 = Xrand, y1 = Ytrue, 
         col = "violetred1", lwd = 1, lty = 3)
  
points(Xtrue,Ytrue, col = "pink", cex = 1.5, pch = 19)
points(Xrand,Ytrue, col = "pink4", cex = 1.5, pch = 19)

axis(1, at=-4:4)
axis(2, at=-4:4)
mtext("X", side = 1, line = 2)
mtext("Y", side = 2, line = 2)

legend("topleft", 
       legend = c("true f", "evaluated f", "residuals", "true Y", "distorted Y"), 
       col = c("seashell4", "violetred3", "violetred1", "pink", "pink4"), 
       lty = c(2, 1, 3, NA, NA), lwd = c(2, 3, 1, NA, NA), 
       pch = c(NA, NA, NA, 19, 19), 
       pt.cex = c(NA, NA, NA, 1.5, 1.5), 
       bty = "n")
```
